### ISSUE TITLE
Ninja Grandmaster Hanzo has no image

### ISSUE THREAD

**Issue by throwaway217** [Ygoproco/Live-images#378]

**Comment by hah4sk** [comment]
I submitted a pull request for this a couple days ago, please let me know if the image I added is sufficient :)

**Comment by AndreOliveiraMendes** [comment]
this issue can be closed now since the [pull](https://github.com/Ygoproco/Live-images/pull/382) was accepted

**Comment by throwaway217** [comment]
I'm going to do a pull when I get home today but I'm closing this now since it's probably solved.
